# category
---
apiVersion: iam.kubesphere.io/v1beta1
kind: Category
metadata:
  labels:
    iam.kubesphere.io/scope: "global"
    kubesphere.io/managed: "true"
  name: manage-app
spec:
  displayName:
    en: 'AppStore Manage'
    zh: '应用商店管理'

---
apiVersion: iam.kubesphere.io/v1beta1
kind: Category
metadata:
  labels:
    iam.kubesphere.io/scope: "workspace"
    kubesphere.io/managed: "true"
  name: workspace-app
spec:
  displayName:
    en: 'Workspace Apps'
    zh: '应用管理'

---
apiVersion: iam.kubesphere.io/v1beta1
kind: Category
metadata:
  labels:
    iam.kubesphere.io/scope: "namespace"
    kubesphere.io/managed: "true"
  name: namespace-app
spec:
  displayName:
    en: 'App Releases'
    zh: '应用'