apiVersion: iam.kubesphere.io/v1beta1
kind: ClusterRole
metadata:
  annotations:
    kubesphere.io/creator: system
  name: cluster-admin
aggregationRoleTemplates:
  roleSelector:
    matchLabels:
      iam.kubesphere.io/scope: "cluster"
  templateNames: []
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
  - nonResourceURLs:
      - '*'
    verbs:
      - '*'

---
apiVersion: iam.kubesphere.io/v1beta1
kind: ClusterRole
metadata:
  annotations:
    kubesphere.io/creator: system
  name: cluster-viewer
aggregationRoleTemplates:
  roleSelector:
    matchLabels:
      iam.kubesphere.io/aggregate-to-cluster-viewer: ""
  templateNames:
    - cluster-view-components
    - cluster-view-volume-snapshot-classes
    - cluster-view-volumes
    - cluster-view-roles
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - get
      - list
      - watch
  - nonResourceURLs:
      - '*'
    verbs:
      - GET