{{ if eq .Values.role "member" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ks-agent
    tier: backend
    version: {{ .Chart.AppVersion }}
  name: ks-agent
spec:
  strategy:
    rollingUpdate:
      maxSurge: 0
    type: RollingUpdate
  progressDeadlineSeconds: 600
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ks-agent
      tier: backend
      # version: {{ .Chart.AppVersion }}
  template:
    metadata:
      labels:
        app: ks-agent
        tier: backend
        # version: {{ .Chart.AppVersion }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - command:
        - ks-apiserver
        - --logtostderr=true
        image: {{ .Values.image.ks_apiserver_repo }}:{{ .Values.image.ks_apiserver_tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: ks-apiserver
        ports:
        - containerPort: 9090
          protocol: TCP
        resources:
          {{- toYaml .Values.apiserver.resources | nindent 12 }}
        volumeMounts:
        - mountPath: /etc/kubesphere/
          name: kubesphere-config
        - mountPath: /etc/localtime
          name: host-time
          readOnly: true
        {{- if .Values.apiserver.extraVolumeMounts }}
          {{- toYaml .Values.apiserver.extraVolumeMounts | nindent 8 }}
        {{- end }}
        env:
        {{- if .Values.env }}
        {{- toYaml .Values.env | nindent 8 }}
        {{- end }}
        livenessProbe:
          failureThreshold: 8
          httpGet:
            path: /kapis/version
            port: 9090
            scheme: HTTP
          initialDelaySeconds: 15
          timeoutSeconds: 15
      - command:
        - controller-manager
        - --logtostderr=true
        - --leader-elect=true
        - --controllers=*,-helmrepo,-helmcategory,-helmapplication,-helmapplicationversion,-helmrelease,-helm,-job,-application
        image: {{ .Values.image.ks_controller_manager_repo }}:{{ .Values.image.ks_controller_manager_tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: ks-controller-manager
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        resources:
          {{- toYaml .Values.controller.resources | nindent 12 }}
        volumeMounts:
        - mountPath: /etc/kubesphere/
          name: kubesphere-config
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: webhook-secret
        - mountPath: /etc/localtime
          name: host-time
          readOnly: true
        {{- if .Values.controller.extraVolumeMounts }}
          {{- toYaml .Values.controller.extraVolumeMounts | nindent 8 }}
        {{- end }}
        env:
        {{- if .Values.env }}
        {{- toYaml .Values.env | nindent 8 }}
        {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccountName: {{ include "ks-core.serviceAccountName" . }}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: kubesphere-config
        configMap:
          name: kubesphere-config
          defaultMode: 420
      - name: webhook-secret
        secret:
          defaultMode: 420
          secretName: ks-controller-manager-webhook-cert
      - hostPath:
          path: /etc/localtime
          type: ""
        name: host-time
      {{- if .Values.controller.extraVolumes }}
        {{ toYaml .Values.controller.extraVolumes | nindent 6 }}
      {{- end }}
      {{- if .Values.apiserver.extraVolumes }}
        {{ toYaml .Values.apiserver.extraVolumes | nindent 6 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{ end }}
