{{- if .Values.config.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubesphere-config
  namespace: kubesphere-system
data:
  kubesphere.yaml: |
    authentication:
      authenticateRateLimiterMaxTries: {{ .Values.config.authentication.authenticateRateLimiterMaxTries | default 10 }}
      authenticateRateLimiterDuration: {{ .Values.config.authentication.authenticationRateLimiterDuration | default "10m0s" }}
      loginHistoryRetentionPeriod: {{ .Values.config.authentication.loginHistoryRetentionPeriod | default "168h"  }}
      maximumClockSkew: {{ .Values.config.authentication.maximumClockSkew | default "10s" }}
      multipleLogin: {{ .Values.config.authentication.enableMultiLogin | default true }}
{{- if eq .Values.role "host" }}
      {{- with lookup "v1" "ConfigMap" (printf "%s" .Release.Namespace) "kubesphere-config" }}
      jwtSecret: "{{ (fromYaml (index .data "kubesphere.yaml")).authentication.jwtSecret }}"
      {{- else }}
      jwtSecret: "{{ .Values.config.jwtSecret | default (randAlphaNum 32 ) }}"
      {{- end }}
{{- else }}
      jwtSecret: "{{ .Values.config.jwtSecret }}"
{{- end }}
{{- if eq .Values.role "member" }}
      oauthOptions:
        accessTokenMaxAge: 0
{{- end }}
    multicluster:
      clusterRole: {{ .Values.role }}
    terminal:
      kubectl:
        image: {{ template "kubectl.image" . }}
      node:
        image:  {{ template "nodeShell.image" . }}
    helmImage: {{ template "helm.image" . }}
{{- if .Values.devMode }}
    telemetry:
      ksCloudUrl: "https://clouddev.kubesphere.io"
{{- end }}
{{- end }}
