apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-post-install"
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: {{ include "ks-core.serviceAccountName" . }}
      containers:
        - name: post-install-job
          image: "kubesphere/kubectl:v1.27.4"
          command:
            - /bin/bash
            - -c
            - |
              for ns in kubesphere-system default kube-system;
              do
                kubectl label ns $ns kubesphere.io/workspace=system-workspace
                kubectl label ns $ns kubesphere.io/managed=true
              done