apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-pre-delete"
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: {{ include "ks-core.serviceAccountName" . }}
      containers:
        - name: pre-delete-job
          image: "kubesphere/kubectl:v1.27.4"
          command:
            - /bin/bash
            - -c
            - |
              kubectl -n kubesphere-system scale deploy ks-controller-manager --replicas=0
              until [ "$(kubectl -n kube-system get deploy ks-controller-manager -o jsonpath='{.status.readyReplicas}')" = "" ];
              do
                echo "ks-controller-manager is running......"
                sleep 1s
              done
              kubectl patch workspaces.tenant.kubesphere.io system-workspace -p '{"metadata":{"finalizers":[]}}' --type=merge
              kubectl patch workspacetemplates.tenant.kubesphere.io system-workspace -p '{"metadata":{"finalizers":[]}}' --type=merge
              for ns in $(kubectl get ns -o jsonpath='{.items[*].metadata.name}')
              do 
                  kubectl label ns $ns kubesphere.io/workspace- && \
                  kubectl patch ns $ns -p '{"metadata":{"ownerReferences":[]}}' --type=merge && \
                  echo "{\"kind\":\"Namespace\",\"apiVersion\":\"v1\",\"metadata\":{\"name\":\"$ns\",\"finalizers\":null}}" | kubectl replace --raw "/api/v1/namespaces/$ns/finalize" -f - 
              done
  
  
