name: Release Drafter

on:
  push:
    branches:
      - master
      - kse-3.x
      - ksc

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}